# Generated by Django 4.1.7 on 2023-09-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumb',
            field=models.ImageField(default='thumb.jpg', upload_to='category/thumb/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumb',
            field=models.ImageField(default='thumb.jpg', upload_to='products/thumb/'),
        ),
    ]
