# Generated by Django 4.1.7 on 2023-09-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_category_thumb_alter_product_thumb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Review',
        ),
        migrations.AddField(
            model_name='category',
            name='body',
            field=models.TextField(blank=True, default=None, verbose_name='content'),
        ),
    ]
